services:
  - type: web
    name: momobot-cg-api
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    region: oregon
    rootDir: .           
    startCommand: ""    
    autoDeploy: true
    envVars:
      - key: AZURE_OPENAI_ENDPOINT
        fromSecret: AZURE_OPENAI_ENDPOINT
      - key: AZURE_OPENAI_API_KEY
        fromSecret: AZURE_OPENAI_API_KEY
      - key: AZURE_DEPLOYMENT_NAME
        fromSecret: AZURE_DEPLOYMENT_NAME
