rootDir: &rootDir backend

services:
  - type: web
    name: momobot-cg-api
    env: python
    pythonVersion: 3.12
    plan: free
    region: oregon
    buildCommand: |
      cd *rootDir
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: cd *rootDir &&uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    envVars:
      - key: AZURE_OPENAI_ENDPOINT
        fromSecret: AZURE_OPENAI_ENDPOINT
      - key: AZURE_OPENAI_API_KEY
        fromSecret: AZURE_OPENAI_API_KEY
      - key: AZURE_DEPLOYMENT_NAME
        fromSecret: AZURE_DEPLOYMENT_NAME
